name: "Publish module"

inputs: 
  orasVersion:
    required: true
    default: '1.3.0'
  cosignVersion:
    required: true
    default: '2.6.1'

runs:
  using: "composite"
  steps:
    - name: Install ORAS
      shell: pwsh
      run: |
        orasVersion="${{ inputs.orasVersion }}"
        orasUrl="https://github.com/oras-project/oras/releases/download/v${orasVersion}/oras_${orasVersion}_linux_amd64.tar.gz"
        installDir="${{ github.workspace }}/tools/oras"
        tarPath="${{ runner.temp }}/oras.tar.gz"

        echo "Creating installation directory..."
        mkdir -p "$installDir"

        echo "Downloading ORAS v${orasVersion}..."
        echo "From: $orasUrl"
        curl -sL "$orasUrl" -o "$tarPath"

        echo "Extracting ORAS..."
        tar -xzf "$tarPath" -C "$installDir"

        echo "Cleaning up temporary files..."
        rm -f "$tarPath"

        # Add to PATH for all subsequent tasks in this job
        echo "Adding ORAS to PATH..."
        echo "$installDir" >> $GITHUB_PATH

        echo "Verifying ORAS installation..."
        "$installDir/oras" version
    - name: Install Cosign
      shell: pwsh
      run: |
        cosignVersion="${{ inputs.cosignVersion }}"
        cosignUrl="https://github.com/sigstore/cosign/releases/download/v${cosignVersion}/cosign-linux-amd64"
        installDir="${{ github.workspace }}/tools/cosign"

        echo "Creating installation directory..."
        mkdir -p "$installDir"

        echo "Downloading cosign v${cosignVersion}..."
        cosignPath="$installDir/cosign"
        curl -sL "$cosignUrl" -o "$cosignPath"
        chmod +x "$cosignPath"

        # Add to PATH for all subsequent tasks in this job
        echo "Adding cosign to PATH..."
        echo "$installDir" >> $GITHUB_PATH

        echo "Verifying cosign installation..."
        "$cosignPath" version